name: Build Dolphin

on:
  push:
    paths:
      - '.github/workflows/dolphin.yml'
      - 'dolphin/PKGBUILD'
  workflow_dispatch:

jobs:
  build-and-package-dolphin:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base

    steps:
    - name: Update system and install build dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel

    - name: Clone repo for PKGBUILD
      run: |
         cd
         git clone https://github.com/buildingpkgs/pkgs.git

    - name: Build Dolphin (and kio for it)
      run: |
        cd
        sed -i 's/^#MAKEFLAGS/MAKEFLAGS/' /etc/makepkg.conf
        useradd user -mG wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chown user -R .
        cd pkgs/kio
        su user -c "yes|PKGDEST=/tmp/dolphin makepkg --noconfirm -si"
        cd
        cd pkgs/dolphin
        su user -c "yes|PKGDEST=/tmp/dolphin makepkg --noconfirm -s"

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: dolphin
        path: |
            /tmp/dolphin/*.zst
