name: wine-staging

on:
  push:
    paths:
      - '.github/workflows/wine-staging.yml'
      - 'wine-staging/PKGBUILD'
  workflow_dispatch:

jobs:
  build-and-package-wine-staging:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base

    steps:
    - name: Update system and install build dependencies
      run: |
        pacman -Syu --noconfirm git base-devel

    - name: Clone repo for PKGBUILD
      run: |
         git clone https://github.com/buildingpkgs/pkgs.git

    - name: Build wine-staging
      run: |
        sed -i 's/^#MAKEFLAGS/MAKEFLAGS/' /etc/makepkg.conf
        useradd user -mG wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chown user -R .
        cd pkgs/wine-staging
        su user -c "yes|PKGDEST=/tmp/wine-staging makepkg --noconfirm -s"

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: wine-staging
        path: |
            /tmp/wine-staging/*.zst
